#!/usr/bin/env perl
# https://metacpan.org/pod/XML::LibXML
# https://metacpan.org/pod/XML::LibXML::NodeList

use v5.12;

if ( !@ARGV ) {
    die "No files given!";
}

for (@ARGV) {

    open my $fh, '<', $_ or die "Can't open file: $!";

    use XML::LibXML;
    use XML::LibXML::NodeList;
    my $dom = XML::LibXML->load_xml( IO => $fh );

    foreach my $node (
        $dom->findnodes(
            '//script[@id="socks-open-proxy" and contains(@output, "status: open")]'
        )->get_nodelist
        )
    {
        my $address = $node->find('../../../address/@addr')->to_literal;
        my $port    = $node->find('../@portid')->to_literal;
        my $hostname
            = $node->find('../../../hostnames/hostname/@name')->to_literal;

        say $address, "\t", $port, "\t", $hostname;
    }
}

