#!/usr/bin/env sh
export PATH=".:/usr/local/bin:/usr/bin:/bin"
session="open-services"
args="-f tmux.conf"
tmux="$(command -v tmux) $args" || tmux="/usr/bin/tmux $args"
$tmux has-session -t $session
if [ $? -eq 0 ]; then
	cat <<!
Session $session already exists. Attaching."
!
	sleep 1
	$tmux attach -t $session
	exit 0;
fi
$tmux new-session -d -s $session
$tmux new-window -t $session:0 
$tmux send-keys -t $session:0 'cat targets.txt targets.d/*.txt | shuf | nice xargs -I{} -P8 ./scan {}' C-m
$tmux split-window  -h -t $session:0
$tmux send-keys -t $session:0 'watch ./show-progress' C-m
$tmux split-window  -v -t $session:0
$tmux send-keys -t $session:0 'cat README' C-m
$tmux attach-session -t $session
